apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-psmdb-operator
  # The namespace where the ArgoCD application resource itself lives
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.20.1 # Use the latest stable version
    chart: psmdb-operator
  destination:
    server: https://kubernetes.default.svc
    # The namespace where the Percona Operator pods will be deployed
    namespace: percona-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true